### ISSUE TITLE
[TODO] before publish

### ISSUE THREAD

**Issue by mrjvs** [mrjvs/neat-config#13]
- [x] Test error handling of file loading (soft fail or throw?)
 - [x] export all types that are useful for devs using the library
 - [ ] gather feedback from friends, see if I missed anything
 - [ ] resolve #4
